# Generated by Django 4.1.8 on 2023-04-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="link",
        ),
    ]
