# Generated by Django 3.1.1 on 2023-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20230514_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.ManyToManyField(blank=True, null=True, to='application.Location'),
        ),
    ]
