# Generated by Django 4.2.1 on 2023-05-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20230528_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='bookmarkers',
        ),
        migrations.AddField(
            model_name='post',
            name='memory_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
