# Generated by Django 4.2.1 on 2023-05-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_remove_post_bookmarkers_post_memory_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='memory_date',
        ),
        migrations.AddField(
            model_name='post',
            name='memory_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='memory_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
